### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by kevinludwig** [mbuhot/eskotlin#11]
I'm unable to use this library because of various ClassNotFoundExceptions. An example stack trace:

```
java.lang.ClassNotFoundException: org.elasticsearch.index.query.Operator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_91]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_91]
	at mbuhot.eskotlin.query.fulltext.MatchKt.match(Match.kt:50) ~[eskotlin-0.3.0.jar:na]
	at com.demo.search.services.QueryBuilder.termMatch(QueryBuilder.kt:18) ~[main/:na]
	at com.demo.search.services.QueryBuilder$build$1.invoke(QueryBuilder.kt:56) ~[main/:na]
	at com.demo.search.services.QueryBuilder$build$1.invoke(QueryBuilder.kt:8) ~[main/:na]
	at mbuhot.eskotlin.query.compound.BoolKt.bool(Bool.kt:37) ~[eskotlin-0.3.0.jar:na]
	at com.demo.search.services.QueryBuilder.build(QueryBuilder.kt:53) ~[main/:na]
	at com.demo.search.services.SearchService.search(SearchService.kt:42) ~[main/:na]
	at com.demo.search.controllers.SearchController.search(SearchController.kt:23) ~[main/:na]
```

**Comment by mbuhot** [comment]
Please include the version of `eskotlin` and `elasticsearch` packages that you are using.

**Comment by kevinludwig** [comment]
I'm using the latest published, 0.3.0 of eskotlin. I'm using latest Elasticsearch server, however I'm using direct REST calls via Spring's RestTemplate, so the only elastic search library that I pull in is ESKotlin (which itself pulls in elasticsearch 5.0.0 I believe).

**Comment by mbuhot** [comment]
Looks like a classpath issue from the stacktrace.

The [Operator](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/query/Operator.java#L31) enum definitely exists in the `elasticsearch` library: 

Does adding an explicit dependency on elasticsearch get it working?

eg:

```groovy
compile "org.elasticsearch:elasticsearch:5.0.0"
```

**Comment by mbuhot** [comment]
Closing - I don't think this is an issue in ESKotlin, but something to do with how spring boot manages the elasticsearch dependency.
